version: '3'

services:
    jenkins:
        image: getintodevops/jenkins-withdocker:lts
        container_name: jenkins_cicd
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /jenkins:/var/jenkins_home
            - /home/ubuntu/media-community-cert:/var/media-community-cert
        ports:
            - "9090:8080"
            - "50000:50000"
        user: root