spring:
  profiles:
    group:
      "dev": "common, oauth, dev, devOauth"
      "prod": "common, oauth, prod, prodOauth"
    active: dev

jasypt:
  encryptor:
#    password: password
    bean: jasyptStringEncryptor

cloud:
  aws:
    credentials:
      accessKey: ENC(8x2SySHHil1bw9KvbsYqZNsbwCaDkYMxDordejUtaq0=)
      secretKey: ENC(U/twQBZQyRj5KdnFGZHGiZ0g4NpEafjB65rB8NeREptkqRTAS6EjawbDvBIB459ZZosGZL3sW9w=)
    S3:
      bucket: dremean

path:
  img: static/img/

---

spring:
  config:
    activte:
      on-profile: "common"
  messages:
    basename: errors
