spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/community?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
    username: "root"
    password: "134679"

---
spring:
  config:
    activate:
      on-profile: "devOauth"
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirectUri: http://localhost:8080/login/oauth2/code/kakao
