spring:
  profiles:
    group:
      "dev": "common, oauth, dev, devOauth"
      "prod": "common, oauth, prod, prodOauth"
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: false
#    open-in-view: false
logging.level:
  org.hibernate.SQL: debug


jasypt:
  encryptor:
#    password: password
    bean: jasyptStringEncryptor

cloud:
  aws:
    credentials:
      accessKey: ENC(8x2SySHHil1bw9KvbsYqZNsbwCaDkYMxDordejUtaq0=)
      secretKey: ENC(U/twQBZQyRj5KdnFGZHGiZ0g4NpEafjB65rB8NeREptkqRTAS6EjawbDvBIB459ZZosGZL3sW9w=)
    S3:
      bucket: dremean

path:
  img: static/img/

---

spring:
  config:
    activte:
      on-profile: "common"
  messages:
    basename: errors
