spring:
  config:
    activate:
      on-profile: "oauth"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(gGpIGnEuu22aDGSabJqsrJ7vRCscLteWwKoibx1SlXlDZMWq2cu3baQlnlZqVwYM7sN3OrrR61bdLEocRBloOp06PMukUnE1HySmmiVTOOs=)
            client-secret: ENC(xo+qkuyTZzWevioM4YspvTncviO4VwEin3BlUrTyLGe6jLTA3pDdsd9+9pNSTGak)
            scope: profile, email
          kakao:
            clientId: ENC(rMB410fsgvQ6OfVYmB5zlCx8BYHBRnWz/uDbtt/HABfnAc4aVkqnDL0zTXSX6R16)
            clientSecret: ENC(rGvG/hkThR4SQkUGgoLTs8ZSaK+ejSHdOD+vOStv0GO+btdq4pbuV01WW+TRbWBY)
            clientAuthentication-method: Post
            scope: profile_nickname, profile_image, account_email
            clientName: Kakao
            authorizationGrantType: authorization_code
#            redirectUri: http://localhost:8080/login/oauth2/code/kakao
        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id