spring:
  profiles:
    group:
      "dev": "common, oauth, dev, devOauth"
      "prod": "common, oauth, prod, prodOauth"
    active: prod

---

spring:
  config:
    activte:
      on-profile: "common"
  messages:
    basename: errors
