spring:
  config:
    activate:
      on-profile: "oauth"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 826900381-078ctivsr4j9kpg250vg6j9a7jejla76.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          kakao:
            clientId: 846e578cc2e14ad0325827f9f46b9dd5
            clientSecret: hXjgvqFdfB6ELDfpKVhJKhb7FeSQBNdn
            clientAuthentication-method: Post
            scope: profile_nickname, profile_image, account_email
            clientName: Kakao
            authorizationGrantType: authorization_code
#            redirectUri: http://localhost:8080/login/oauth2/code/kakao
        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id