spring:
  profiles:
    group:
      "dev": "common, oauth, dev, devOauth"
      "prod": "common, oauth, prod, prodOauth"
    active: dev

jasypt:
  encryptor:
#    password: password
    bean: jasyptStringEncryptor
---

spring:
  config:
    activte:
      on-profile: "common"
  messages:
    basename: errors
